// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var RieMap = require("../src/RieMap.bs.js");

Jest.describe("Inline: Functions (f form only)", (function (param) {
        Jest.test("make", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* tuple */[
                              "PLN",
                              393
                            ],
                            /* tuple */[
                              "USD",
                              100
                            ]
                          ], Jest.Expect[/* expect */0](RieMap.make(/* array */[
                                    "PLN",
                                    "USD"
                                  ], /* array */[
                                    393,
                                    100
                                  ])));
              }));
        return Jest.test("keys", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* array */[
                                  "PLN",
                                  "USD"
                                ], Jest.Expect[/* expect */0](RieMap.keys(/* array */[
                                          /* tuple */[
                                            "PLN",
                                            393
                                          ],
                                          /* tuple */[
                                            "USD",
                                            100
                                          ]
                                        ])));
                    }));
      }));

Jest.describe("Inline: Operators", (function (param) {
        Jest.test("@:", (function (param) {
                return Jest.Expect[/* toEqual */12](393, Jest.Expect[/* expect */0](RieMap.Operators[/* @: */0](/* array */[/* tuple */[
                                      "PLN",
                                      393
                                    ]], "PLN")));
              }));
        Jest.test("@|", (function (param) {
                return Jest.Expect[/* toEqual */12](82, Jest.Expect[/* expect */0](RieMap.Operators[/* @| */1](/* array */[/* tuple */[
                                      "PLN",
                                      393
                                    ]], /* tuple */[
                                    "GBP",
                                    82
                                  ])));
              }));
        Jest.test("@:!", (function (param) {
                return Jest.Expect[/* toEqual */12](393, Jest.Expect[/* expect */0](RieMap.Operators[/* @:! */2](/* array */[/* tuple */[
                                      "PLN",
                                      393
                                    ]], "PLN")));
              }));
        Jest.test("@-", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[/* tuple */[
                              "USD",
                              100
                            ]], Jest.Expect[/* expect */0](RieMap.Operators[/* @- */3](/* array */[
                                    /* tuple */[
                                      "PLN",
                                      393
                                    ],
                                    /* tuple */[
                                      "USD",
                                      100
                                    ]
                                  ], "PLN")));
              }));
        Jest.test("@++", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* tuple */[
                              "PLN",
                              393
                            ],
                            /* tuple */[
                              "GBP",
                              82
                            ],
                            /* tuple */[
                              "USD",
                              100
                            ]
                          ], Jest.Expect[/* expect */0](RieMap.Operators[/* @++ */4](/* array */[/* tuple */[
                                      "PLN",
                                      393
                                    ]], /* array */[
                                    /* tuple */[
                                      "GBP",
                                      82
                                    ],
                                    /* tuple */[
                                      "USD",
                                      100
                                    ]
                                  ])));
              }));
        Jest.test("@+", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* tuple */[
                              "PLN",
                              393
                            ],
                            /* tuple */[
                              "GBP",
                              82
                            ]
                          ], Jest.Expect[/* expect */0](RieMap.Operators[/* @+ */5](/* array */[/* tuple */[
                                      "PLN",
                                      393
                                    ]], /* tuple */[
                                    "GBP",
                                    82
                                  ])));
              }));
        Jest.test("@#", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* tuple */[
                              "PLN",
                              390
                            ],
                            /* tuple */[
                              "USD",
                              100
                            ]
                          ], Jest.Expect[/* expect */0](RieMap.Operators[/* @# */6](/* array */[
                                    /* tuple */[
                                      "PLN",
                                      393
                                    ],
                                    /* tuple */[
                                      "USD",
                                      100
                                    ]
                                  ], /* tuple */[
                                    "PLN",
                                    390
                                  ])));
              }));
        Jest.test("@#>", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[/* tuple */[
                              "PLN",
                              200
                            ]], Jest.Expect[/* expect */0](RieMap.Operators[/* @#> */7](/* array */[/* tuple */[
                                      "PLN",
                                      100
                                    ]], /* tuple */[
                                    "PLN",
                                    (function (c) {
                                        return (c << 1);
                                      })
                                  ])));
              }));
        Jest.test("@>>:", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* tuple */[
                              "USD",
                              100
                            ],
                            /* tuple */[
                              "GBP",
                              82
                            ]
                          ], Jest.Expect[/* expect */0](RieMap.Operators[/* @>>: */9](/* array */[
                                    /* tuple */[
                                      "PLN",
                                      393
                                    ],
                                    /* tuple */[
                                      "USD",
                                      100
                                    ],
                                    /* tuple */[
                                      "GBP",
                                      82
                                    ]
                                  ], /* array */[
                                    "USD",
                                    "GBP"
                                  ])));
              }));
        Jest.test("$:", (function (param) {
                return Jest.Expect[/* toEqual */12](1, Jest.Expect[/* expect */0](RieMap.Operators[/* $: */10](/* array */[
                                    /* tuple */[
                                      "Nil:01",
                                      0
                                    ],
                                    /* tuple */[
                                      "Pol:01",
                                      1
                                    ]
                                  ], (/^Pol/))));
              }));
        return Jest.test("$::", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* array */[
                                  /* tuple */[
                                    "Pol:01",
                                    1
                                  ],
                                  /* tuple */[
                                    "Pol:02",
                                    2
                                  ]
                                ], Jest.Expect[/* expect */0](RieMap.Operators[/* $:: */11](/* array */[
                                          /* tuple */[
                                            "Nil:01",
                                            0
                                          ],
                                          /* tuple */[
                                            "Pol:01",
                                            1
                                          ],
                                          /* tuple */[
                                            "Pol:02",
                                            2
                                          ]
                                        ], (/^Pol/))));
                    }));
      }));

/*  Not a pure module */
