// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var ReMap = require("../src/ReMap.bs.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var fetchedKittens = /* array */[
  /* tuple */[
    "Fluffykins#001",
    /* array */[
      /* tuple */[
        "Age",
        "3"
      ],
      /* tuple */[
        "Breed",
        "Ragdoll"
      ]
    ]
  ],
  /* tuple */[
    "Fluffykins#002",
    /* array */[
      /* tuple */[
        "Age",
        "1"
      ],
      /* tuple */[
        "Breed",
        "Ragdoll"
      ]
    ]
  ],
  /* tuple */[
    "Toby#001",
    /* array */[
      /* tuple */[
        "Age",
        "3"
      ],
      /* tuple */[
        "Breed",
        "Birman"
      ]
    ]
  ]
];

Jest.describe("README Example", (function (param) {
        Jest.test("Get Fluffykins (@:)", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* tuple */[
                              "Age",
                              "3"
                            ],
                            /* tuple */[
                              "Breed",
                              "Ragdoll"
                            ]
                          ], Jest.Expect[/* expect */0](ReMap.Operators[/* @: */0](fetchedKittens, "Fluffykins#001")));
              }));
        Jest.test("Get Fluffykins (@:!)", (function (param) {
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* tuple */[
                              "Age",
                              "3"
                            ],
                            /* tuple */[
                              "Breed",
                              "Ragdoll"
                            ]
                          ], Jest.Expect[/* expect */0](ReMap.Operators[/* @:! */2](fetchedKittens, "Fluffykins#001")));
              }));
        Jest.test("Get age (@:!)", (function (param) {
                var fk = ReMap.Operators[/* @:! */2](fetchedKittens, "Fluffykins#001");
                return Jest.Expect[/* toEqual */12]("3", Jest.Expect[/* expect */0](ReMap.Operators[/* @:! */2](fk, "Age")));
              }));
        Jest.test("Update age (@#)", (function (param) {
                var fk = ReMap.Operators[/* @:! */2](fetchedKittens, "Fluffykins#001");
                var newKittens = ReMap.Operators[/* @# */6](fetchedKittens, /* tuple */[
                      "Fluffykins#001",
                      ReMap.Operators[/* @# */6](fk, /* tuple */[
                            "Age",
                            "4"
                          ])
                    ]);
                return Jest.Expect[/* toEqual */12](/* array */[
                            /* tuple */[
                              "Fluffykins#001",
                              /* array */[
                                /* tuple */[
                                  "Age",
                                  "4"
                                ],
                                /* tuple */[
                                  "Breed",
                                  "Ragdoll"
                                ]
                              ]
                            ],
                            /* tuple */[
                              "Fluffykins#002",
                              /* array */[
                                /* tuple */[
                                  "Age",
                                  "1"
                                ],
                                /* tuple */[
                                  "Breed",
                                  "Ragdoll"
                                ]
                              ]
                            ],
                            /* tuple */[
                              "Toby#001",
                              /* array */[
                                /* tuple */[
                                  "Age",
                                  "3"
                                ],
                                /* tuple */[
                                  "Breed",
                                  "Birman"
                                ]
                              ]
                            ]
                          ], Jest.Expect[/* expect */0](newKittens));
              }));
        return Jest.test("Update dynamic age (@#>)", (function (param) {
                      var newKittens = ReMap.Operators[/* @#> */7](fetchedKittens, /* tuple */[
                            "Fluffykins#001",
                            (function (fluffykins) {
                                return ReMap.Operators[/* @# */6](fluffykins, /* tuple */[
                                            "Age",
                                            String(Caml_format.caml_int_of_string(ReMap.Operators[/* @:! */2](fluffykins, "Age")) + 1 | 0)
                                          ]);
                              })
                          ]);
                      return Jest.Expect[/* toEqual */12](/* array */[
                                  /* tuple */[
                                    "Fluffykins#001",
                                    /* array */[
                                      /* tuple */[
                                        "Age",
                                        "4"
                                      ],
                                      /* tuple */[
                                        "Breed",
                                        "Ragdoll"
                                      ]
                                    ]
                                  ],
                                  /* tuple */[
                                    "Fluffykins#002",
                                    /* array */[
                                      /* tuple */[
                                        "Age",
                                        "1"
                                      ],
                                      /* tuple */[
                                        "Breed",
                                        "Ragdoll"
                                      ]
                                    ]
                                  ],
                                  /* tuple */[
                                    "Toby#001",
                                    /* array */[
                                      /* tuple */[
                                        "Age",
                                        "3"
                                      ],
                                      /* tuple */[
                                        "Breed",
                                        "Birman"
                                      ]
                                    ]
                                  ]
                                ], Jest.Expect[/* expect */0](newKittens));
                    }));
      }));

exports.fetchedKittens = fetchedKittens;
/*  Not a pure module */
